### ISSUE TITLE
新）dockerマルチステージビルド

### ISSUE THREAD

**Issue by shari-sushi** [shari-sushi/V-Kara-Lists#127]
現状でフロントのみデプロイしブラウザからアクセスできるようになった。
その結果、ECSにて$1.5/dほど請求が来ており、6000円/月を超える計算である。(ここ数日は150円弱/$)
辛い。
(バックエンドもデプロイしたらどうなるんだ…。)

<image src="https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/8a42e2c1-fec8-4eff-9b7a-29dd4e9089b9" width="300px" />
<image src="https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/8e181ff7-39e0-40e4-b6da-48eb63e8e512" width="200px" />

<br ></br >
FargateのECSはタスク定義で指定したvCPUとメモリの確保分が料金に影響する。
…どの程度か分からないが。
[AWS Fargate の料金](https://aws.amazon.com/jp/fargate/pricing/)
> AWS Fargate の料金は、使用された vCPU、メモリ、オペレーティングシステム、CPU アーキテクチャ1、およびストレージ リソースに基づいて計算され、計算期間はコンテナイメージのダウンロードを開始した時点から Amazon ECS タスクまたは Amazon EKS2 ポッドが終了するまでで、最も近い秒数に切り上げられます。

現状でタスク定義上では`1GB vCPU, 3GBメモリ`になっているが、
フロントだけということもあり、せいぜい3%ほどのようである。
(そもそも使用者は自分だけだが)
タスク定義の作成では最低値は0.25GB, 1GBだが、
### vCPU値はimageサイズよりも小さくできない。

Dockerのマルチビルドを導入しイメージサイズを小さくする。
```
現状のECR上のimageサイズ
go: 457.49MB
next: 778.11MB
```

**Comment by sharin-sushi** [comment]
### ちなみにFargate見積

1GB, 3GBで: `0.04 USD/month`
十分安いが？？？？
```
Number of tasks or pods: 1 per day * (730 hours in a month / 24 hours in a day) = 30.42 per month
Average duration: 1 minutes = 0.02 hours
Pricing calculations
30.42 tasks x 1 vCPU x 0.02 hours x 0.05056 USD per hour = 0.03 USD for vCPU hours
30.42 tasks x 3.00 GB x 0.02 hours x 0.00553 USD per GB per hour = 0.01 USD for GB hours
20 GB - 20 GB (no additional charge) = 0.00 GB billable ephemeral storage per task
0.03 USD for vCPU hours + 0.01 USD for GB hours = 0.04 USD total
Fargate cost (monthly): 0.04 USD
```

0.5GB, 1GB: `0.00 USD` もはや算出不可能レベルになったが？？
```
Number of tasks or pods: 1 per day * (730 hours in a month / 24 hours in a day) = 30.42 per month
Average duration: 1 minutes = 0.02 hours
Pricing calculations
30.42 tasks x 0.50 vCPU x 0.02 hours x 0.05056 USD per hour = 0.02 USD for vCPU hours
20 GB - 20 GB (no additional charge) = 0.00 GB billable ephemeral storage per task
Fargate cost (monthly): 0.00 USD
```

え、もしかしてコスト嵩む原因はこれではない？
ならマルチステージビルドやる意味ほぼないな…。

ちなみに
参考
- [AWS 見積](https://calculator.aws/#/createCalculator/Fargate?nc2=pr)
- Zenn [Next.js アプリケーションの ECS へのデプロイについて考えるスレ](https://zenn.dev/snaka/scraps/dbe838e44d1b71)
- Qiita [Next.jsのstand alone buildを利用したdocker imageのbuild](https://qiita.com/ryuseiyarou/items/ed9209cce81906903baf)

**Comment by sharin-sushi** [comment]
現状、マルチビルドしなくてとGoのimageは.25GB切ってるから不要か？

それはそれとして参考
https://qiita.com/greenteabiscuit/items/72d28a3dd17f0a60689d

## デプロイすらままならないので、デプロイ成功してからマルチビルド検討し直します

**Comment by sharin-sushi** [comment]
デプロイで来たのでメモ

### メモ
  - imageの容量
  - タスク定義で指定したサーバー能力
  - ツイートがバズった日＝一番アクセスが多かったと思われる日の負荷
  (20時ポスト投稿、22時～1時くらいまでがピーク、翌日14時くらいにまたピークと思われる)
---
###  app
471.34MB
CPU .5vCPU, メモリ 1 GB
24h
![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/b1c90a97-d483-44c5-9622-0cc252edb224)
48h(最後にサービス更新、デプロイ強制しちゃったから見ずらくなった)
![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/18f8acb5-e8bc-463a-a321-0d70e8a4a05b)


### api
471.34MB
CPU .5vCPU, メモリ 1 GB
48h
![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/61e06362-0957-4ce1-9364-491025a21df4)

どっちももう１段階は下げたいな
とくにapi

**Comment by sharin-sushi** [comment]
![Screenshot_20240303_154357_Chrome.jpg](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/02a687db-3271-42fa-94ad-85b7b9538557)

![Screenshot_20240303_154445_Chrome.jpg](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/9baf587e-27d1-431b-a5d3-4f0cdbae7f68)

![Screenshot_20240303_151656_Chrome.jpg](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/9f93942d-b579-46e5-8bfd-403415e637c0)

![Screenshot_20240303_152357_Chrome.jpg](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/d0caf772-0c55-45bc-a87e-b09c85c3ae13)

**Comment by sharin-sushi** [comment]
### 追加メモ
3/1 ~ 3/13まで
なお、グラフで隠れている部分も含め、3/2 ~ 3/13は同額である。*画像２枚目参照
3/13分は反映が中途半端なだけと思われる。

![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/7dbff14b-4f00-4b4c-a68c-dff3769961c3)
![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/e68c4892-9706-4b78-877f-32cdfec31252)

**Comment by sharin-sushi** [comment]
ELBが無料分超過してたらしい
これが前回コメントの`AWSデータ転送量`の超過の結果なのだろうか？（そのうち調べる）
![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/7b9e9a97-cb13-4cbe-925a-c272ee54bb86)

![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/daed4215-b247-4445-933d-3cb4753c7a2c)

**Comment by sharin-sushi** [comment]
3月分まとめ

![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/774313f3-5f39-47e3-980e-a845cce8f7c9)

![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/9903f824-37c5-4b27-83c3-88922fcfa33c)

**Comment by sharin-sushi** [comment]
いただいたアドバイス
キャッシュにおける静的な何かってない？
next.jsをcloud fronとs3に切り替える？

**Comment by shari-sushi** [comment]
api何故か重くなった…
大したことしてないと思うんだが
![image](https://github.com/shari-sushi/V-Kara-Lists/assets/127638412/fa3d655c-795a-4874-94a3-84deb4edd77e)

**Comment by shari-sushi** [comment]
TODO
- [x] マルチステージビルドでローカルで動作確認
- [x] マルチステージビルド本番環境で動作確認
- [x] 新規タスク定義、↑で動いてた定義のjsonをコピー、一部↓に変更し再デプロイ


### ローカル、本番で動作確認
Goだけマルチステージビルドできた。
(てか世間の人のコピペで済むみたい)
20分の1近くになったわ…。
これでawsのメモリか何かを１つ下の最低レベルに下げられる＝apiのECS料金半額
（最近料金体系変わったので不確かだけど）
![image](https://github.com/user-attachments/assets/7411691e-bd09-4792-b2e8-762e6a1c648e)

- before
  ![image](https://github.com/user-attachments/assets/97956a6d-8cb5-4db5-a9f4-61a34bee31ce)
- jst7時：image容量だけ下げた
  ![image](https://github.com/user-attachments/assets/8411f5d1-7117-4fda-95b8-ee0c6eac62a6)
 1, 2分くらいで切り替わる…早くなってる？
  <image src="https://github.com/user-attachments/assets/fd7ca970-7ce8-4305-b349-b22750474ec4" width="150px"/>

- jst9時: cpu, vメモリも下げた(タスク定義変えた)
  <image src="https://github.com/user-attachments/assets/2cb21fe8-02a2-4f5c-9e30-5df00fa3c8f1" width="140px"/>


### 新規タスク定義
(従来は cpu, vメモリを 0.5GB, 1024MB だった)
```json
      "cpu": "256",
      "memory": "512",
      
      "//": "containerDefinitions ...  [ ... logConfiguration.options",
        "awslogs-group": "/ecs/v-kara-api-definition-025vCPU05GB-p8080",
        
      "family": "v-kara-api-definition-025vCPU05GB-p8080",
```
taskDefinitionArn, revision, status, requiresAttributes, compatibilities, registeredAt, registeredBy
はaws側が設定するものらしいのでコピペ段階では削除する。

**Comment by shari-sushi** [comment]
え、osとリージョン変えるだけでも2割くらい安くなる！？
![image](https://github.com/user-attachments/assets/b7410775-3998-46ce-8025-306f5ffb1907)

![image](https://github.com/user-attachments/assets/d48f84b5-34ef-4471-a975-4f3994f897a6)


![image](https://github.com/user-attachments/assets/b60e5a6d-d52c-4977-aea3-b58b81ac8cf6)

**Comment by shari-sushi** [comment]
結果、api側だけで＄９(ドル円145.5)の削減になった。
app側もやる。

**Comment by shari-sushi** [comment]
# Next.js のDocker multiple stage build 

[Dockerfileベストプラクティス - Node.jsアプリケーション編](https://qiita.com/sakurasan/items/02ca5ea47dd4f1725e0d)
をとりあえずコピペした。
<details><summary>npm ci でエラー</summary>
<p>

```
 => [deps 3/4] COPY ./package*.json ./                                                                                                                              0.3s
 => ERROR [deps 4/4] RUN npm ci                                                                                                                                     0.8s
------
 > [deps 4/4] RUN npm ci:
0.763 npm error code EUSAGE
0.764 npm error
0.764 npm error The `npm ci` command can only install with an existing package-lock.json or
0.764 npm error npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
0.764 npm error later to generate a package-lock.json file, then try again.
0.764 npm error
0.764 npm error Clean install a project
0.764 npm error
0.764 npm error Usage:
0.764 npm error npm ci
0.764 npm error
0.764 npm error Options:
0.764 npm error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
0.764 npm error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
0.764 npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
0.764 npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
0.764 npm error [--no-bin-links] [--no-fund] [--dry-run]
0.764 npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
0.764 npm error [-ws|--workspaces] [--include-workspace-root] [--install-links]
0.764 npm error
0.764 npm error aliases: clean-install, ic, install-clean, isntall-clean
0.764 npm error
0.764 npm error Run "npm help ci" for more info
0.766 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-02T19_41_05_369Z-debug-0.log
------
Dockerfile:11
--------------------
   9 |     
  10 |     COPY ./package*.json ./
  11 | >>> RUN npm ci
  12 |     
  13 |     # builder ステージ
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci" did not complete successfully: exit code: 1
```
</p>
</details> 

pathが違ったので修正(2, 3か所)。
見本だとmyappにdockerfile置いてたみたい。まじか。
また、このエラーによりlockファイルの` lockfileVersion,`が1以上じゃないとnpm ciが使えないことを知る。
そしてその過程で、dockerのnodeとpackage.json生成時(ローカル環境のnode)のバージョンが違うことに気づいく。念のためローカル環境に合わせた。

<details><summary>`npx prisma generate` でエラー</summary>
<p>

```bash
=> [deps 4/4] RUN npm ci                                                                     18.1s
 => ERROR [builder 2/5] COPY --from=deps ./myapp/node_modules ./node_modules                   0.0s
------
 > [builder 2/5] COPY --from=deps ./myapp/node_modules ./node_modules:
------
Dockerfile:16
--------------------
  14 |     FROM base AS builder
  15 |     WORKDIR /app
  16 | >>> COPY --from=deps ./myapp/node_modules ./node_modules
  17 |     COPY . .
  18 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref a37fbb6c-3477-40ef-bebf-4f3d9e271faf::59o09m5kkzpj7r2lroqx6tcuc: failed to walk /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount1541922500/myapp: lstat /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount1541922500/myapp: no such file or directory
```
</p>
</details> 

prisma@5.20.0  をinstallしろって言われてる。
docker環境内でビルドしたいだけなのにローカルでinstall必要なのか。

Vercel(Next開発元)の見本有ったわ。prisma使ってないが？
https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

なのでprismaの1文削除。
今後、これ参考に全部書き換える。
<details><summary>npm run build でエラー</summary>
<p>
```
=> [builder 3/4] COPY . .                                                                    17.1s
 => ERROR [builder 4/4] RUN npm run build                                                      1.1s
------                                                                                              
 > [builder 4/4] RUN npm run build:
1.085 npm error code ENOENT
1.085 npm error syscall open
1.086 npm error path /app/package.json
1.086 npm error errno -2
1.087 npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/app/package.json'
1.087 npm error enoent This is related to npm not being able to find a file.
1.087 npm error enoent
1.088 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-02T20_11_07_048Z-debug-0.log
------
Dockerfile:21
--------------------
  19 |     COPY . .
  20 |     
  21 | >>> RUN npm run build
  22 |     
  23 |     # runner ステージ
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 254
```

</p>
</details> 

pathが悪そう。
```diff
- RUN npm run build
+ RUN cd /app/myapp && npm run build
```

```
 => [builder 4/4] RUN cd /app/myapp && npm run build                                          22.8s
 => ERROR [runner 4/8] COPY --from=builder /app/public ./public                                0.0s 
 => CACHED [runner 5/8] RUN mkdir .next                                                        0.0s 
 => CACHED [runner 6/8] RUN chown nextjs:nodejs .next                                          0.0s 
 => ERROR [runner 7/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./      0.0s
 => ERROR [runner 8/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/st  0.0s
------
 > [runner 4/8] COPY --from=builder /app/public ./public:
------
------
 > [runner 7/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./:
------
------
 > [runner 8/8] COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static:
------
Dockerfile:38
--------------------
  36 |     
  37 |     COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
  38 | >>> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
  39 |     
  40 |     USER nextjs
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref a37fbb6c-3477-40ef-bebf-4f3d9e271faf::vhdo8uzcfckieqyxav4pr6t5n: failed to walk /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount1831560562/app/.next: lstat /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount1831560562/app/.next: no such file or directory
```

ミスった部分の公式dockerfileに`https://nextjs.org/docs/pages/api-reference/next-config-js/output`への誘導コメントがあった。
```diff
# /myapp/next.config.js
const nextConfig = {
  reactStrictMode: true,
+  output: "standalone",
};

module.exports = nextConfig;
``` 
※.jsonにコメントは書けないです。

同じエラー出たわ。無関係なのか？

---

portをAWS(ALB?)で設定した数字にする。

**Comment by shari-sushi** [comment]
goのサンプル…？
https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

Docker公式にもあったけどよくわからないので…。


また、go mod install, go mod tidy, npm install が全部永遠に終わらないバグに遭遇した。
PC再起したら解消したので永遠の謎。

**Comment by shari-sushi** [comment]
```
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY myapp/package*.json ./
RUN npm ci;

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .


# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN cd /app/myapp && npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/myapp/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/myapp/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/myapp/.next/static ./.next/static

USER nextjs

EXPOSE 80

ENV PORT=80

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
ENV HOSTNAME="0.0.0.0"
CMD ["sudo", "node", "server.js"]

#############################
# single stage build
# ##########
# FROM node:18-alpine

# WORKDIR /app

# COPY ./myapp .

# RUN npm install

# EXPOSE 80

# # ↓ならRUN npm run build必要（だけどちゃんと機能してない。pathが悪いかも？）
# RUN npm run build
# CMD ["npm", "run", "start"]

# # ↓ならRUN npm run build不要（だけど遅いDoockerだと顕著だし、本番環境と遠い）
# # CMD ["npm", "run", "dev"]
```

**Comment by shari-sushi** [comment]
```
# FROM golang:1.18-alpine

# WORKDIR /api/src

# COPY . .

# RUN go mod tidy

# EXPOSE 8080

# CMD [ "go","run","cmd/main.go" ]


#### ビルドステージ ####
FROM golang:1.18-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# C言語との統合を防いで少しでも軽くする…らしい。
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/main.go

#### 実行ステージ ####
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# 重要：ビルドされたmainのみをコピー
COPY --from=builder /build/main .

EXPOSE 8080

CMD ["./main"]
```

**Comment by shari-sushi** [comment]
### フロントエンド
- #260 
  port変更した方が良いことが分かったので、aws対応推奨となった
